//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace HRISv2.Models
{
    public partial class HRISMonitoringEntities : DbContext
    {
        public HRISMonitoringEntities()
            : base("name=HRISMonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tappActionDetail> tappActionDetails { get; set; }
        public virtual DbSet<tappAction> tappActions { get; set; }
        public virtual DbSet<tappFAQ> tappFAQs { get; set; }
        public virtual DbSet<tappOffice> tappOffices { get; set; }
        public virtual DbSet<trefQuestion> trefQuestions { get; set; }
        public virtual DbSet<trefRemark> trefRemarks { get; set; }
    }
}
