//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace HRISv2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class HRISEntities : DbContext
    {
        public HRISEntities()
            : base("name=HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tappEmpGroup> tappEmpGroup { get; set; }
        public DbSet<tAttEmpArea> tAttEmpArea { get; set; }
        public DbSet<tAttEmpScheme> tAttEmpScheme { get; set; }
        public DbSet<tAttScheme> tAttScheme { get; set; }
        public DbSet<tAttStationArea> tAttStationArea { get; set; }
        public DbSet<trefEmpGroup> trefEmpGroup { get; set; }
        public DbSet<vUserProfile> vUserProfile { get; set; }
        public DbSet<vUserProfileWithUsername> vUserProfileWithUsername { get; set; }
        public DbSet<vUserProfileWithServices> vUserProfileWithServices { get; set; }
        public DbSet<tappServiceRecord> tappServiceRecord { get; set; }
        public DbSet<tappEmployee> tappEmployee { get; set; }
        public DbSet<tappPosition> tappPosition { get; set; }
        public DbSet<tappEmpStatus> tappEmpStatus { get; set; }
        public DbSet<tappOffice> tappOffice { get; set; }
        public DbSet<tappSalarySchem> tappSalarySchem { get; set; }
        public DbSet<tappSalarySched> tappSalarySched { get; set; }
    
        [EdmFunction("HRISEntities", "fnGetEmployeeServiceRecords")]
        public virtual IQueryable<fnGetEmployeeServiceRecords_Result> fnGetEmployeeServiceRecords(string eic)
        {
            var eicParameter = eic != null ?
                new ObjectParameter("eic", eic) :
                new ObjectParameter("eic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetEmployeeServiceRecords_Result>("[HRISEntities].[fnGetEmployeeServiceRecords](@eic)", eicParameter);
        }
    }
}
