//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace HRISv2.Models
{
    public partial class tappAction
    {
        public tappAction()
        {
            this.tappActionDetails = new HashSet<tappActionDetail>();
        }
    
        public int Id { get; set; }
        public int faqId { get; set; }
        public int remarksId { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual ICollection<tappActionDetail> tappActionDetails { get; set; }
        public virtual tappFAQ tappFAQ { get; set; }
        public virtual trefRemark trefRemark { get; set; }
    }
}
