//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tappServiceRecord
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string dateTo { get; set; }
        public string designation { get; set; }
        public string statusName { get; set; }
        public string officeServiceRec { get; set; }
        public string branch { get; set; }
        public string lwpay { get; set; }
        public Nullable<decimal> salaryPayroll { get; set; }
        public Nullable<decimal> salaryServiceRec { get; set; }
        public string paySchemeCode { get; set; }
        public string paySchemeName { get; set; }
        public string sepCause { get; set; }
        public string officeCode { get; set; }
        public string isGovernmentService { get; set; }
        public string isInsideGovernment { get; set; }
        public string SgStep { get; set; }
        public Nullable<int> isApproved { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string approvedEIC { get; set; }
        public string positionCode { get; set; }
        public string subPositionCode { get; set; }
        public string subPosition { get; set; }
    }
}
