//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAttScheme
    {
        public int recNo { get; set; }
        public string SchemeCode { get; set; }
        public string SchemeName { get; set; }
        public string Valid_In1 { get; set; }
        public string In1 { get; set; }
        public string Valid_Out1 { get; set; }
        public string Out1 { get; set; }
        public string Valid_In2 { get; set; }
        public string In2 { get; set; }
        public string Valid_Out2 { get; set; }
        public string Out2 { get; set; }
        public string SchemeDesc { get; set; }
        public Nullable<int> isShifting { get; set; }
        public Nullable<System.TimeSpan> timeIn1 { get; set; }
        public Nullable<System.TimeSpan> timeOut1 { get; set; }
        public Nullable<System.TimeSpan> timeIn2 { get; set; }
        public Nullable<System.TimeSpan> timeOut2 { get; set; }
    }
}
