//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace HRISv2.Models
{
    public partial class tlogUser
    {
        public int recNo { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string EIC { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
