//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace HRISv2.Models
{
    public partial class trefRemark
    {
        public trefRemark()
        {
            this.tappActions = new HashSet<tappAction>();
        }
    
        public int Id { get; set; }
        public int value { get; set; }
        public string detail { get; set; }
    
        public virtual ICollection<tappAction> tappActions { get; set; }
    }
}
