//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trefEmpGroup
    {
        public int recNo { get; set; }
        public string empGroupCode { get; set; }
        public string groupName { get; set; }
        public string officeCode { get; set; }
    }
}
