//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAttDTR
    {
        public int RecNo { get; set; }
        public string DtrID { get; set; }
        public string EIC { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Tag { get; set; }
        public string approveEIC { get; set; }
        public Nullable<int> statusID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> dtStamp { get; set; }
        public string userEIC { get; set; }
        public Nullable<int> timesTardy { get; set; }
        public Nullable<int> timesUnder { get; set; }
        public string wTotTardy { get; set; }
        public string wTotUnder { get; set; }
        public Nullable<int> timesAWOL { get; set; }
        public Nullable<int> timesPassSlip { get; set; }
        public Nullable<int> Tardy { get; set; }
        public Nullable<int> Undertime { get; set; }
        public string transCode { get; set; }
        public string empGroupCode { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string fullnameLast { get; set; }
        public string groupName { get; set; }
        public string statusName { get; set; }
        public string @class { get; set; }
        public Nullable<decimal> dayTardy { get; set; }
        public Nullable<decimal> dayUnder { get; set; }
    }
}
