//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserProfile
    {
        public long ID { get; set; }
        public string IDNo { get; set; }
        public string EIC { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthplace { get; set; }
        public string Position { get; set; }
        public string SubPosition { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string JobStatus { get; set; }
        public string BATSArea { get; set; }
        public string AttendanceScheme { get; set; }
        public string groupName { get; set; }
        public string GroupCode { get; set; }
        public string SchemeCode { get; set; }
        public string AreaID { get; set; }
    }
}
